version: 2.1

# Define the jobs we want to run for this project
orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.5
  checkov: bridgecrew/checkov@0.0.4
jobs:
  build:
    executor: checkov/default
    steps:
      - checkout
      - checkov/scan:
          directory: .
          api-key: BC_API_KEY
          prisma-api-url: https://api.prismacloud.io
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
