version: 2.1
orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.5
  
executors: # Define an executor
  my-executor:
    docker:
      - image: cimg/base:2024.01
# Define the jobs we want to run for this project
jobs:
  build:
    executor: checkov/default
    steps:
      - checkout
      - checkov/scan:
          directory: .
          api-key-variable: 345b1568-06ac-40a4-9ee4-c85f63737f8a::DpeukOQPv2GRHirlin2L6ivgrSE=
          prisma-api-url: https://api.prismacloud.io
  
  test:
    executor: my-executor
    steps:
      - checkout
      - run: echo "test"
  deploy:
    executor: my-executor
    steps:
      - checkout
      - run: echo "deploy"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
