# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

#Integrate Prisma Cloud CICD Runs
orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.5
  checkov: bridgecrew/checkov-orb@0.0.3
jobs:
  build:
    executor: checkov/default
    steps:
      - checkout
      - checkov/scan:
          directory: .
          api-key-variable: 345b1568-06ac-40a4-9ee4-c85f63737f8a::DpeukOQPv2GRHirlin2L6ivgrSE=
          prisma-api-url: https://api.prismacloud.io
