version: 2.1

# Define the jobs we want to run for this project
orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.5
jobs:
  build:
    parallelism: 4
    executor: bridgecrew/default
    steps:
      - checkout
      - bridgecrew/scan:
          directory: .
          api-key-variable: BC_API_KEY 
          prisma-api-url: https://api.prismacloud.io
      - store_test_results:
        path: test-results

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
