version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    executor: checkov/default
    steps:
      - checkout
      - checkov/scan:
          directory: .
          api-key-variable: 345b1568-06ac-40a4-9ee4-c85f63737f8a::DpeukOQPv2GRHirlin2L6ivgrSE=
          prisma-api-url: https://api.prismacloud.io
orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.5
  checkov: bridgecrew/checkov-orb@0.0.3
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
