---
version: 2.1
orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.5
jobs:
  build:
    parallelism: 10
    executor: bridgecrew/default
    steps:
      - checkout
      - bridgecrew/scan:
          directory: .
          api-key-variable: BC_API_KEY
          prisma-api-url: https://api.prismacloud.io
workflows:
  build_and_test: null
  context: my-restricted-context
  jobs:
    - build
